config/routes.rb
Station::Application.routes.draw do

  root :to => "welcome#index", :via => :get

  devise_for :users

  match '/home' => 'welcome#home', :as => :dashboard
  
  resources :gas_stations, :controller => :stations do
  end

  resources :cars, :path => "", :except => [:index] do
    member do
      get :preview
    end

    resources :tanking do
    end
  end
  match '/cars' => 'cars#index', :as => :cars_index
  
  
  resources :stats do
    collection do
      get :expense
      get :gas_stations
    end
  end  

end

app/controllers/tanking_controller.rb
class TankingController < ApplicationController

  before_filter :authenticate_user!

  def index
    @tanking_logs = TankingLog.all
  end

  def show
  end

  def new
    @car = Car.by_slug(params[:car_id])
  end

  def create

    @car = Car.by_slug(params[:car_id])
    @gas_station = GasStation.where(:name => params[:tanking_log][:gas_station]).first

    @tanking_log = TankingLog.new(params[:tanking_log])
    @tanking_log.car = @car if @car
    @tanking_log.gas_station = @gas_station if @gas_station
    
    if @tanking_log.save
      flash[:notice] = "tanking_log was created successfully!"
      redirect_to dashboard_url
    else
      flash[:notice] = "Oops, try again"
      redirect_to dashboard_url
    end
    
  end

end

app/helpers/tanking_helper.rb
module TankingHelper
end

app/views/tanking/_form.html.haml
.page-header
  %h1
    = "New Tanking Log for #{@car.brand} - #{@car.model} - #{@car.year} "

= form_for(:tanking_log, :url => car_tanking_index_url(@car.slug), html: {class: 'form-horizontal', id: 'new_tanking_log'}) do |f|
  .control-group
    = f.label :gas_station, class: 'control-label'
    .controls
      .gas_station_list_container.pull-left
        = f.select :gas_station, []
      .help-inline
        = link_to "add gas station", "#new_gas_station_modal", "data-url" => new_gas_station_url, role: 'button', class: 'btn btn-mini btn-success new_gas_station', "data-toggle" => 'modal'
  .control-group
    = f.label :cost, class: 'control-label'
    .controls
      = f.number_field :cost, :min => 0, class: 'required number'
  .control-group
    = f.label :date, class: 'control-label'
    .controls
      = f.text_field :date, class: 'datepicker'
  .control-group
    = f.label :gallon, class: 'control-label required number'
    .controls
      = f.number_field :gallon, :min => 0, class: 'required'
  .control-group
    = f.label :km, class: 'control-label'
    .controls
      = f.number_field :km, class: 'required'
  .form-actions    
    = f.submit "Create", :class => "btn btn-primary tanking_log"

app/views/tanking/new.html.haml
= render :partial => "form"

-content_for :modal do
  #new_gas_station_modal.modal.hide.fade
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h3 Add Gas Station
    .modal-body
      = render :partial => "stations/form"
    .modal-footer
      %a.btn{:href => "#", "data-dismiss" => "modal"} Close
      %a.btn.btn-primary.create_gas_station{:href => gas_stations_url} Save

-content_for :js do
  :javascript
    Tanking.getGasStations();